name: Lint Code

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          echo "Linting Python files..."
          find . -type f -name "*.py" -exec flake8 {} +
          echo "Linted all Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint
        run: |
          echo "Linting JavaScript files..."

          if [ -d "./server/database" ]; then
            find ./server/database -type f -name "*.js" -exec jshint {} +
          else
            echo "Directory ./server/database not found"
            exit 1
          fi

          echo "Linted all JavaScript files successfully"
